

comment_create = {
    'message': '',  # string(length: 2-500)
    'owner': '',    # string(User Id)
    'post': '',     # string(Post Id)
    }

comment = {
    'id': '',           # string(autogenerated)
    'message': '',      # string(length: 2-500)
    'owner': '',        # object(User Preview)
    'post': '',         # string(Post Id)
    'publishDate': ''   # string(autogenerated)
    }