from src.baseclasses.builder import BuilderBaseClass


class Comment(BuilderBaseClass):

    def __init__(self):
        super().__init__()
        self.reset()

    def set_message(self, message='This can only be imagined'):
        self.result['message'] = message
        return self

    def set_owner(self, owner='id'):
        self.result['owner'] = owner
        return self

    def set_post(self, post='id'):
        self.result['post'] = post
        return self

    def reset(self):
        self.set_message()
        self.set_owner()
        self.set_post()
        return self


# comment_create = {
#     'message': '',  # string(length: 2-500)
#     'owner': '',    # string(User Id)
#     'post': '',     # string(Post Id)
#     }
#
# comment = {
#     'id': '',           # string(autogenerated)
#     'message': '',      # string(length: 2-500)
#     'owner': '',        # object(User Preview)
#     'post': '',         # string(Post Id)
#     'publishDate': ''   # string(autogenerated)
#     }
