from src.baseclasses.builder import BuilderBaseClass


class Post(BuilderBaseClass):

    def __init__(self):
        super().__init__()
        self.reset()

    def set_text(self, text='Being dead is not a problem. Being forgotten is what it is'):
        self.result['text'] = text
        return self

    def set_image(self, image='https://oir.mobi/uploads/posts/2020-01/1578314523_4-7.jpg'):
        self.result['image'] = image
        return self

    def set_likes(self, likes=123):
        self.result['likes'] = likes
        return self

    def set_tags(self, tags=['philosophy', 'quotes']):
        self.result['tags'] = tags
        return self

    def set_owner(self, owner="id"):
        self.result['owner'] = owner
        return self

    def reset(self):
        self.set_text()
        self.set_image()
        self.set_likes()
        self.set_tags()
        self.set_owner()
        return self


# post_create = {
#     'text': '',     # string(length: 6-50, preview only)
#     'image': '',    # string(url)
#     'likes': '',    # number(init value: 0)
#     'tags': '',     # array(string)
#     'owner': ''     # string(User id)
#     }
#
# post_preview = {
#     'id': '',           # string(autogenerated)
#     'text': '',         # string(length: 6-50, preview only)
#     'image': '',        # string(url)
#     'likes': '',        # number(init value: 0)
#     'tags': '',         # array(string)
#     'publishDate': '',  # string(autogenerated)
#     'owner': ''         # object(User Preview)
#     }
#
# post = {
#     'id': '',            # string(autogenerated)
#     'text': '',          # string(length: 6-1000)
#     'image': '',         # string(url)
#     'likes': '',         # number(init value: 0)
#     'link': '',          # string(url, length: 6-200)
#     'tags': '',          # array(string)
#     'publishDate': '',   # string(autogenerated)
#     'owner': ''          # object(User Preview)
#     }

# post = Post().result
# print(post)
