
post_create = {
    'text': '',     # string(length: 6-50, preview only)
    'image': '',    # string(url)
    'likes': '',    # number(init value: 0)
    'tags': '',     # array(string)
    'owner': ''     # string(User id)
    }

post_preview = {
    'id': '',           # string(autogenerated)
    'text': '',         # string(length: 6-50, preview only)
    'image': '',        # string(url)
    'likes': '',        # number(init value: 0)
    'tags': '',         # array(string)
    'publishDate': '',  # string(autogenerated)
    'owner': ''         # object(User Preview)
    }

post = {
    'id': '',            # string(autogenerated)
    'text': '',          # string(length: 6-1000)
    'image': '',         # string(url)
    'likes': '',         # number(init value: 0)
    'link': '',          # string(url, length: 6-200)
    'tags': '',          # array(string)
    'publishDate': '',   # string(autogenerated)
    'owner': ''          # object(User Preview)
    }




